query ProductComments($slug: String!) {
  products(where: { slug: $slug }) {
    slug
    id
    comments {
      content
      points
      authorId
      authorUser {
        id
        email
        username
        provider
      }
      authorType
      authorName
      authorEmail
      authorAvatar
    }
  }
}
