query Product($slug: String!) {
  products(where: { slug: $slug }) {
    id
    title
    description
    price
    image {
      url
      formats
    }
    slug
    productcategories {
      name
      slug
      id
    }
  }
}
