query Articles($slug: String!) {
  articles(where: { slug: $slug }) {
    slug
    id
    article_content {
      subtitle
      content
      header_image {
        url
        previewUrl
      }
    }
    published
    published_at
    unpublish_date
  }
}
