query BlogCategory($slug: String!) {
  blogCategories(where: { slug: $slug }) {
    articles {
      id
      title
      slug
      content
      blogcategories {
        name
        slug
      }
      headerImage {
        url
      }
    }
  }
}
