query Articles($slug: String!) {
  articles(where: { slug: $slug }) {
    slug
    id
    content {
      subtitle
      content
      header_image {
        url
      }
    }
    published_at
    unpublish_date
  }
}
